spring:
  application:
    name: gateway

server:
  port: ${SERVER_PORT:8090}

services:
  backend:
    base-url: ${BACKEND_BASE_URL:http://localhost:8091}

management:
  endpoints:
    web:
      exposure:
        include: health,info
